<?php

/**
 * @file
 * AUP Customization
 * Various Drupal customizations
 */

/**
 * Implements hook_help().
 */
function aup_custom_help($path, $arg) {
  switch ($path) {
    case "admin/help#aup_custom":
      return '<p>' . t("Various Drupal customizations")
      . '</p>';
    break;
  }
}

/**
 * Implements hook_menu().
 */
function aup_custom_menu() {
  $items = array();

  $items['admin/config/aup'] = array(
    'title' => 'AUP',
    'description' => 'Settings for modules developed by AUP.',
    'position' => 'left',
    'weight' => -15,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  return $items;
}

/**
 * TODO
 *
 * @return bool
 *   TRUE TODO
 */
function aup_custom_task_start() {
  $trace = debug_backtrace();
  $caller = array_shift($trace);
  $caller = array_shift($trace);
  if (!$function = $caller['function']) {
	  watchdog('aup_custom', 'Missing calling function', array(), WATCHDOG_ERROR);
	  return FALSE;
	}
	watchdog($function, 'Task started');
}

/**
 * TODO
 *
 * @return bool
 *   TRUE TODO
 */
function aup_custom_task_end($report = array(), $rc = WATCHDOG_INFO) {
	$trace = debug_backtrace();
	$caller = array_shift($trace);
	$caller = array_shift($trace);
	if (!$function = $caller['function']) {
		watchdog('aup_custom', 'Missing calling function', array(), WATCHDOG_ERROR);
		return FALSE;
	}
	
	// Report e-mail.
	$id = $function . '_mail';
	$site_name = variable_get('site_name', '');
	$site_mail = variable_get('site_mail', '');
	$from = "$site_name <$site_mail>";
	$subject =  variable_get($function . '_mail_subject', "Report of $function");
	$to = variable_get($function . '_mail_to', $site_mail);
	$body = implode('<br/>', $report);

	switch ($rc) {
		case WATCHDOG_ERROR:
			$subject = "[ERROR] $subject";
			break;
	
		case WATCHDOG_WARNING:
			$subject = "[WARNING] $subject";
			break;
				
	}
	
	$message = array(
			'id' => $id,
			'to' => $to,
			'subject' => $subject,
			'body' => array($body),
			'headers' => array(
					'From' => $from,
					'Sender' => $from,
					'Return-Path' => $site_mail,
			),
	);
	$system = drupal_mail_system($id, '');
	$message = $system->format($message);
	
	if (!$system->mail($message)) {
		$rc = WATCHDOG_ERROR;
		$report[] = t('[ERROR] Unable to send the report by e-mail');
	}
	
	$msg = t('Task finished @status:<br/>!report', array(
			'@status' => ($rc == WATCHDOG_ERROR) ? 'with error(s)' :
			(($rc == WATCHDOG_WARNING) ? 'with warning(s)' :
					'successfully'),
			'!report' => implode('<br/>', $report)));
	watchdog($function, $msg, array(), $rc);
	drupal_set_message($msg);
	
	return ($rc == WATCHDOG_INFO ? TRUE : FALSE);
}
