<?php

# MODULE BOOTSTRAP
require_once(drupal_get_path('module', 'aup_implementation').'/includes/aup_implementation.helper.inc');
require_once('includes/home.admin.inc');

/**
 * Implementation of hook_theme
 */
function home_theme($existing, $type, $theme, $path) {

	$theme = array();
	$path = drupal_get_path('module', 'home') .'/theme';

	$theme['home_slideshow'] = array(
		'arguments' => array('nodes' => null),
		'template' => 'home-slideshow',
		'path' => $path,
	);

	return $theme;
	
}

/**
 * Implementation of hook_permission
 */
function home_permission() {
	
	$perms = array();
	  
	$perms['administer home'] = array(
	    'title' => t('Administer the Homepage Settings'),
	  );
	  
	return $perms;
	
}

/**
 * Implementation of hook_menu
 */
function home_menu() {
	
	$items = array();
	
	$items['admin/config/mstoner/home'] = array(
		'title' => 'Home',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('home_administration'),
		'access arguments' => array('administer home'),
		'type' => MENU_NORMAL_ITEM,
		'weight' => -50
	);
	
	return $items;
	
}
	    
/**
 * Implementation of hook_preprocess_page
 */
function home_preprocess_page(&$variables) {
	
	if ($variables['is_front']) {
		
		
		$slideshow_nodes = new NodequeueNodes(variable_get('home_slideshow_qid', 0));
		
		if(count($slideshow_nodes->getNodes()) >= 2)
			$variables['show_arrows'] = 1;
		else
			$variables['show_arrows'] = 0;
			
		$variables['home_slideshow'] = theme('home_slideshow', array('nodes' => $slideshow_nodes->getNodes()));

	}
	
}