<?php 

# MODULE BOOTSTRAP
require_once(drupal_get_path('module', 'aup_implementation').'/includes/aup_implementation.helper.inc');
require_once('includes/aup_implementation.admin.inc');
require_once('includes/aup_implementation.theme.inc');

/**
 * Implementation of hook_theme
 */
function aup_implementation_theme($existing, $type, $theme, $path) {

	$theme = array();
	$path = drupal_get_path('module', 'aup_implementation') .'/theme';

	$theme['news_events_slideshow'] = array(
		'arguments' => array('nodes' => null),
		'template' => 'news-events-slideshow',
		'path' => $path,
	);
	
	$theme['aup_support_slideshow_treatment'] = array(
		'arguments' => array('queue' => null),
		'template' => 'aup-support-slideshow-treatment',
		'path' => $path,
	);
	
	$theme['aup_admissions_features_treatment'] = array(
		'arguments' => array('queue' => null),
		'template' => 'aup-features-treatment',
		'path' => $path,
	);
	
	$theme['aup_right_column_accordion_treatment'] = array(
		'arguments' => array('queue' => null),
		'template' => 'aup-right-column-accordion-treatment',
		'path' => $path,
	);
	
	$theme['support_slideshow'] = array(
		'arguments' => array('nodes' => null),
		'template' => 'support-slideshow',
		'path' => $path,
	);
	
	$theme['admissions_features'] = array(
		'arguments' => array('nodes' => null),
		'template' => 'admissions-features',
		'path' => $path,
	);
	
	$theme['right_column_accordion'] = array(
		'arguments' => array('nodes' => null),
		'template' => 'right-column-accordion',
		'path' => $path,
	);

	return $theme;
	
}

/**
 * Implementation of hook_permission
 */
function aup_implementation_permission() {
	
	$perms = array();
	  
	$perms['administer news events'] = array(
	    'title' => t('Administer the News Events Settings'),
	  );
	  
	return $perms;
	
}

/**
 * Implementation of hook_menu
 */
function aup_implementation_menu() {
	
	$items = array();
	
	$items['admin/config/mstoner/news-events'] = array(
		'title' => 'News And Events',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('news_events_administration'),
		'access arguments' => array('administer news events'),
		'type' => MENU_NORMAL_ITEM,
		'weight' => -49
	);
	
	return $items;
	
}

/**
 * Implementation of hook_nodequeue_block_treatments()
 */
function aup_implementation_nodequeue_block_treatments() {
	
	$treatments = array();
	
	$treatments['support_slideshow_treatment'] = array(
		'name' => t('Support Page Slideshow'),
		'theme_hook' => 'aup_support_slideshow_treatment',
	);
	
	$treatments['admissions_features_treatment'] = array(
		'name' => t('Admissions Page Features'),
		'theme_hook' => 'aup_admissions_features_treatment',
	);
	
	$treatments['right_column_accordion_treatment'] = array(
		'name' => t('Right Column Accordion (SPIF'),
		'theme_hook' => 'aup_right_column_accordion_treatment',
	);
	
	return $treatments;
	
}